# Optional: Add funding information if you want to accept donations
# Uncomment and customize as needed

# github: yourusername
# patreon: yourusername
# open_collective: yourusername
# ko_fi: yourusername
# custom: ['https://your-donation-url.com']
