#!/bin/bash
# Example usage scenarios for Cursor Chat Recovery Kit
# These are safe examples that won't modify your actual workspace

echo "📚 Cursor Chat Recovery Kit - Usage Examples"
echo "=========================================="
echo ""
echo "These examples demonstrate common use cases."
echo "Replace placeholder names with your actual project names."
echo ""

echo "1. MIGRATE AFTER FOLDER RENAME"
echo "-------------------------------"
echo "# You renamed 'MyOldProject' to 'MyNewProject'"
echo "./bin/restore_chat_history.sh auto 'MyOldProject' 'MyNewProject'"
echo ""

echo "2. LIST AVAILABLE BACKUPS"
echo "-------------------------"
echo "# See what backups you have"
echo "./bin/restore_chat_history.sh list-backups"
echo "# Or with alias:"
echo "cursor-backups"
echo ""

echo "3. EXPLORE WORKSPACES"
echo "---------------------"
echo "# List current workspaces"
echo "./bin/restore_chat_history.sh list-workspaces"
echo ""
echo "# List workspaces in a specific backup"
echo "./bin/restore_chat_history.sh list-workspaces 20251219_160000"
echo ""

echo "4. FIND WORKSPACE ID"
echo "-------------------"
echo "# Find the workspace ID for a project"
echo "./bin/restore_chat_history.sh find 'MyProject'"
echo ""

echo "5. MANUAL BACKUP"
echo "---------------"
echo "# Create a quick backup"
echo "./bin/quick_backup.sh"
echo "# Or with alias:"
echo "cursor-backup"
echo ""

echo "6. SET UP AUTOMATIC BACKUPS"
echo "---------------------------"
echo "# Configure backups every 4 hours"
echo "./bin/setup_cron.sh"
echo ""

echo "7. EMERGENCY RECOVERY"
echo "--------------------"
echo "# Diagnose workspace issues"
echo "./bin/emergency_recovery.sh diagnose"
echo ""
echo "# List available recovery points"
echo "./bin/emergency_recovery.sh list"
echo ""
echo "# Restore from backup"
echo "./bin/emergency_recovery.sh restore 20251219_160000"
echo ""

echo "8. EXPORT CHATS TO MARKDOWN"
echo "----------------------------"
echo "# Export latest backup"
echo "./bin/convert_chats_to_markdown.sh latest"
echo ""
echo "# Export specific backup"
echo "./bin/convert_chats_to_markdown.sh backup 20251219_160000"
echo ""

echo "9. SET UP ALIASES"
echo "----------------"
echo "# Install convenient command aliases"
echo "./bin/setup_aliases.sh"
echo "source ~/.zshrc  # or restart terminal"
echo ""

echo "10. SESSION LOGGING"
echo "-------------------"
echo "# Start logging a development session"
echo "./bin/session_logger.sh start 'Feature Development'"
echo ""
echo "# Add a note"
echo "./bin/session_logger.sh note 'Fixed bug in parser'"
echo ""
echo "# End session"
echo "./bin/session_logger.sh end 'Ready for testing'"
echo ""

echo "⚠️  REMEMBER: Always close Cursor before running migration or restore operations!"
